let resenasProfesor=[]; let filtroResenas='pending';
function escR(v){const d=document.createElement('div');d.textContent=v??'';return d.innerHTML;}
function starsR(v){return '★'.repeat(v)+'☆'.repeat(5-v)}
function estadoR(s){return ({pending:'Pendiente',approved:'Publicada',rejected:'Rechazada'})[s]||s}
async function initProfesorResenas(){if(!window.auth?.requireAuth('profesor'))return;const s=window.auth.getCurrentUser();await window.navegacion.initNavegacion('profesor','resenas',s.nombre);await cargarResenasProfesor();renderProfesorResenas();}
async function cargarResenasProfesor(){const {data,error}=await window.supabaseClient.from('resenas').select('id, usuario_id, valoracion, comentario, status, created_at, updated_at, usuarios(nombre,email)').order('created_at',{ascending:false});if(error)throw error;resenasProfesor=data||[];}
function renderProfesorResenas(){const c=document.getElementById('resenas-container');const counts={pending:0,approved:0,rejected:0};resenasProfesor.forEach(r=>counts[r.status]=(counts[r.status]||0)+1);const items=resenasProfesor.filter(r=>r.status===filtroResenas);c.innerHTML=`<section class="resenas-hero"><div><h2>⭐ Gestión de reseñas</h2><p>Aprueba, rechaza y revisa las experiencias enviadas por alumnos que completaron el curso.</p></div></section><div class="resenas-tabs">${[['pending','Pendientes'],['approved','Publicadas'],['rejected','Rechazadas']].map(([id,t])=>`<button class="resenas-tab ${filtroResenas===id?'active':''}" data-filter="${id}">${t} (${counts[id]})</button>`).join('')}</div><div class="resenas-admin-list">${items.length?items.map(cardAdmin).join(''):'<div class="resenas-empty">No hay reseñas en este estado.</div>'}</div>`;document.querySelectorAll('.resenas-tab').forEach(b=>b.addEventListener('click',()=>{filtroResenas=b.dataset.filter;renderProfesorResenas()}));document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>cambiarEstado(Number(b.dataset.id),b.dataset.action)));}
function cardAdmin(r){const u=r.usuarios||{};return `<article class="resena-admin-card"><div class="resena-admin-meta"><div><p class="resena-name">${escR(u.nombre||'Alumno')}</p><span class="resena-date">${escR(u.email||'')} · ${new Date(r.created_at).toLocaleDateString('es-ES')}</span></div><span class="resena-status ${r.status}">${estadoR(r.status)}</span></div><div class="resena-stars">${starsR(r.valoracion)}</div><p class="resena-comment">${escR(r.comentario)}</p><div class="resena-admin-actions">${r.status!=='approved'?`<button class="btn-resena success" data-action="approved" data-id="${r.id}">Aprobar y publicar</button>`:''}${r.status!=='rejected'?`<button class="btn-resena danger" data-action="rejected" data-id="${r.id}">Rechazar</button>`:''}${r.status!=='pending'?`<button class="btn-resena secondary" data-action="pending" data-id="${r.id}">Volver a pendiente</button>`:''}</div></article>`}
async function cambiarEstado(id,status){const texto=status==='approved'?'aprobar y publicar':status==='rejected'?'rechazar':'devolver a pendiente';window.modal.confirmar(`¿Quieres ${texto} esta reseña?`,async()=>{const {error}=await window.supabaseClient.from('resenas').update({status,updated_at:new Date().toISOString()}).eq('id',id);if(error){console.error(error);window.modal.mostrar('No se pudo actualizar la reseña','error');return;}window.modal.mostrar(status==='approved'?'Reseña publicada':'Estado actualizado','exito');await cargarResenasProfesor();renderProfesorResenas();});}
document.addEventListener('DOMContentLoaded',()=>initProfesorResenas().catch(err=>{console.error(err);document.getElementById('resenas-container').innerHTML='<div class="resenas-empty">No se pudieron cargar las reseñas. Comprueba la migración de Supabase.</div>';}));
