begin;

create table if not exists public.resenas (
  id bigint generated by default as identity primary key,
  usuario_id text not null references public.usuarios(id) on delete cascade,
  valoracion integer not null check (valoracion between 1 and 5),
  comentario text not null check (char_length(btrim(comentario)) between 10 and 1200),
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  created_at timestamp without time zone not null default now(),
  updated_at timestamp without time zone not null default now(),
  constraint resenas_usuario_unique unique (usuario_id)
);

alter table public.resenas enable row level security;

create schema if not exists private;
create or replace function private.is_profesor()
returns boolean
language sql
stable
security definer
set search_path = public, auth
as $$
  select exists (
    select 1 from public.usuarios
    where id = (select auth.uid())::text and rol = 'profesor'
  );
$$;
revoke all on function private.is_profesor() from public;
grant execute on function private.is_profesor() to authenticated;

drop policy if exists "Alumnos ven resenas aprobadas y propia" on public.resenas;
create policy "Alumnos ven resenas aprobadas y propia"
on public.resenas for select to authenticated
using (status = 'approved' or usuario_id = (select auth.uid())::text or private.is_profesor());

drop policy if exists "Alumno crea su resena al completar curso" on public.resenas;
create policy "Alumno crea su resena al completar curso"
on public.resenas for insert to authenticated
with check (
  usuario_id = (select auth.uid())::text
  and status = 'pending'
  and (select count(*) from public.progreso p where p.usuario_id = (select auth.uid())::text and p.completada = true) >= 14
);

drop policy if exists "Alumno edita su resena" on public.resenas;
create policy "Alumno edita su resena"
on public.resenas for update to authenticated
using (usuario_id = (select auth.uid())::text or private.is_profesor())
with check (usuario_id = (select auth.uid())::text or private.is_profesor());

drop policy if exists "Profesor elimina resenas" on public.resenas;
create policy "Profesor elimina resenas"
on public.resenas for delete to authenticated
using (private.is_profesor());

create or replace function public.prepare_resena()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if not private.is_profesor() then
    new.usuario_id := (select auth.uid())::text;
    new.status := 'pending';
    if tg_op = 'UPDATE' then
      new.created_at := old.created_at;
    end if;
  end if;
  new.updated_at := now();
  return new;
end;
$$;
revoke all on function public.prepare_resena() from public;

drop trigger if exists trg_prepare_resena on public.resenas;
create trigger trg_prepare_resena
before insert or update on public.resenas
for each row execute function public.prepare_resena();

grant select, insert, update, delete on public.resenas to authenticated;
grant usage, select on sequence public.resenas_id_seq to authenticated;

commit;
